import type { Vulnerabilidade, Squad, Notificacao, RegraNotificacao, IntegracaoRtc, HistoricoItem } from './types'

const historicoPadrao: HistoricoItem[] = [
  { data: '2025-01-15', tipo: 'criacao', descricao: 'Vulnerabilidade criada', usuario: 'Sistema' },
  { data: '2025-01-16', tipo: 'status', descricao: 'Status alterado para Em análise', usuario: 'João Silva' },
  { data: '2025-01-18', tipo: 'notificacao', descricao: 'Notificação enviada para squad', usuario: 'Sistema' },
]

export const vulnerabilidades: Vulnerabilidade[] = [
  {
    id: 'VULN-001',
    rtcWorkItemId: 'WI-1234',
    titulo: 'SQL Injection no endpoint de autenticação',
    descricaoExecutiva: 'Falha crítica que permite injeção de comandos SQL através do campo de login, possibilitando acesso não autorizado ao banco de dados.',
    descricaoTecnica: 'O parâmetro username no endpoint /api/auth/login não possui sanitização adequada. Payloads como `\' OR 1=1--` permitem bypass de autenticação.',
    criticidade: 'Crítica',
    scoreCvss: 9.8,
    vetorCvss: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    cwe: 'CWE-89',
    owaspCategory: 'A03:2025-Injection',
    squad: 'API Core',
    responsavel: 'João Silva',
    gestor: 'Maria Santos',
    sistema: 'Portal Administrativo',
    ativo: 'api-gateway',
    componente: 'AuthController',
    ambiente: 'Produção',
    endpoint: '/api/auth/login',
    metodoHttp: 'POST',
    parametroAfetado: 'username',
    evidenciaTextual: 'Payload utilizado: \' OR 1=1-- resultou em bypass completo da autenticação.',
    origem: 'Pentest',
    dataCriacao: '2025-01-10',
    ultimaAtualizacao: '2025-03-01',
    sla: '2025-02-10',
    diasEmAberto: 62,
    recomendacao: 'Implementar prepared statements e validação de entrada. Utilizar ORM com proteção contra injection.',
    tags: ['injection', 'autenticação', 'crítico'],
    reincidencia: 2,
    historico: historicoPadrao,
    notificacoesEnviadas: 5,
    status: 'Aberta',
    comentarios: []
  },
  {
    id: 'VULN-002',
    rtcWorkItemId: 'WI-1235',
    titulo: 'Broken Access Control no painel de administração',
    descricaoExecutiva: 'Usuários com perfil comum conseguem acessar funcionalidades administrativas através de manipulação de parâmetros.',
    descricaoTecnica: 'O endpoint /api/admin/users não valida adequadamente as permissões do usuário logado, permitindo IDOR.',
    criticidade: 'Crítica',
    scoreCvss: 8.6,
    vetorCvss: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:L',
    cwe: 'CWE-639',
    owaspCategory: 'A01:2025-Broken Access Control',
    squad: 'Backend',
    responsavel: 'Ana Costa',
    gestor: 'Pedro Lima',
    sistema: 'Portal Administrativo',
    ativo: 'admin-service',
    componente: 'UserController',
    ambiente: 'Produção',
    endpoint: '/api/admin/users',
    metodoHttp: 'GET',
    parametroAfetado: 'userId',
    origem: 'SCA',
    dataCriacao: '2025-01-15',
    ultimaAtualizacao: '2025-02-28',
    sla: '2025-02-15',
    diasEmAberto: 57,
    recomendacao: 'Implementar validação de autorização no middleware. Adicionar verificação de ownership.',
    tags: ['autorização', 'IDOR', 'admin'],
    reincidencia: 3,
    historico: historicoPadrao,
    notificacoesEnviadas: 4,
    status: 'Em Correção',
    comentarios: []
  },
  {
    id: 'VULN-003',
    rtcWorkItemId: 'WI-1236',
    titulo: 'XSS Stored no módulo de comentários',
    descricaoExecutiva: 'Scripts maliciosos podem ser armazenados e executados no contexto de outros usuários.',
    descricaoTecnica: 'O campo de comentários não sanitiza tags HTML, permitindo injeção de scripts JavaScript que são persistidos no banco.',
    criticidade: 'Alta',
    scoreCvss: 7.2,
    vetorCvss: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:L/A:N',
    cwe: 'CWE-79',
    owaspCategory: 'A03:2025-Injection',
    squad: 'Frontend',
    responsavel: 'Carlos Mendes',
    gestor: 'Maria Santos',
    sistema: 'Portal do Cliente',
    ativo: 'web-app',
    componente: 'CommentsModule',
    ambiente: 'Produção',
    endpoint: '/api/comments',
    metodoHttp: 'POST',
    parametroAfetado: 'content',
    origem: 'Manual',
    dataCriacao: '2025-02-01',
    ultimaAtualizacao: '2025-03-05',
    sla: '2025-03-01',
    diasEmAberto: 40,
    recomendacao: 'Implementar sanitização de HTML com DOMPurify. Utilizar Content Security Policy restritivo.',
    tags: ['XSS', 'frontend', 'sanitização'],
    reincidencia: 1,
    historico: historicoPadrao,
    notificacoesEnviadas: 2,
    status: 'Em Backlog',
    comentarios: []
  },
  {
    id: 'VULN-004',
    titulo: 'Exposição de credenciais em logs',
    descricaoExecutiva: 'Credenciais de API estão sendo registradas em texto plano nos logs da aplicação.',
    descricaoTecnica: 'O middleware de logging captura o body completo das requisições, incluindo tokens e senhas.',
    criticidade: 'Alta',
    scoreCvss: 7.5,
    cwe: 'CWE-532',
    owaspCategory: 'A09:2025-Logging Failures',
    squad: 'DevOps',
    gestor: 'Roberto Alves',
    sistema: 'Microserviços',
    ativo: 'log-service',
    ambiente: 'Produção',
    origem: 'Manual',
    dataCriacao: '2025-02-10',
    ultimaAtualizacao: '2025-03-08',
    sla: '2025-03-10',
    diasEmAberto: 31,
    recomendacao: 'Implementar mascaramento de dados sensíveis no logger. Revisar políticas de retenção.',
    tags: ['logs', 'credenciais', 'compliance'],
    reincidencia: 0,
    historico: historicoPadrao,
    notificacoesEnviadas: 1,
    status: 'Aberta',
    comentarios: []
  },
  {
    id: 'VULN-005',
    rtcWorkItemId: 'WI-1238',
    titulo: 'Certificado SSL próximo do vencimento',
    descricaoExecutiva: 'O certificado SSL do ambiente de produção expira em 15 dias.',
    descricaoTecnica: 'Certificado wildcard *.unisys.com vence em 2025-03-28.',
    criticidade: 'Média',
    scoreCvss: 5.3,
    cwe: 'CWE-295',
    owaspCategory: 'A02:2025-Cryptographic Failures',
    squad: 'Infraestrutura',
    responsavel: 'Lucas Ferreira',
    gestor: 'Roberto Alves',
    sistema: 'Infraestrutura',
    ativo: 'cdn-principal',
    ambiente: 'Produção',
    origem: 'SCA',
    dataCriacao: '2025-03-01',
    ultimaAtualizacao: '2025-03-10',
    sla: '2025-03-25',
    diasEmAberto: 12,
    recomendacao: 'Renovar certificado SSL e configurar automação para renovação futura.',
    tags: ['ssl', 'certificado', 'infraestrutura'],
    reincidencia: 1,
    historico: historicoPadrao,
    notificacoesEnviadas: 2,
    status: 'Em Correção',
    comentarios: []
  },
  {
    id: 'VULN-006',
    titulo: 'Versão desatualizada do framework',
    descricaoExecutiva: 'Framework utilizado possui vulnerabilidades conhecidas na versão atual.',
    descricaoTecnica: 'Spring Boot 2.5.x possui CVEs conhecidas. Recomendada atualização para 3.x.',
    criticidade: 'Média',
    scoreCvss: 6.1,
    cwe: 'CWE-1104',
    owaspCategory: 'A06:2025-Vulnerable Components',
    squad: 'Backend',
    responsavel: 'Ana Costa',
    gestor: 'Pedro Lima',
    sistema: 'API Gateway',
    ativo: 'api-gateway',
    ambiente: 'Produção',
    origem: 'SCA',
    dataCriacao: '2025-02-20',
    ultimaAtualizacao: '2025-03-05',
    sla: '2025-04-20',
    diasEmAberto: 21,
    recomendacao: 'Planejar migração para Spring Boot 3.x com testes de regressão.',
    tags: ['dependências', 'atualização', 'framework'],
    reincidencia: 0,
    historico: historicoPadrao,
    notificacoesEnviadas: 0,
    status: 'Em Reteste',
    comentarios: []
  },
  {
    id: 'VULN-007',
    rtcWorkItemId: 'WI-1240',
    titulo: 'Rate limiting ausente em API pública',
    descricaoExecutiva: 'API pública não possui limitação de requisições, permitindo ataques de força bruta.',
    descricaoTecnica: 'O endpoint /api/public/search permite requisições ilimitadas sem throttling.',
    criticidade: 'Baixa',
    scoreCvss: 4.3,
    cwe: 'CWE-770',
    owaspCategory: 'A05:2025-Security Misconfiguration',
    squad: 'API Core',
    responsavel: 'João Silva',
    gestor: 'Maria Santos',
    sistema: 'API Pública',
    ativo: 'public-api',
    ambiente: 'Produção',
    origem: 'Pentest',
    dataCriacao: '2025-02-25',
    ultimaAtualizacao: '2025-03-08',
    sla: '2025-04-25',
    diasEmAberto: 16,
    recomendacao: 'Implementar rate limiting com Redis. Configurar limites por IP e por usuário.',
    tags: ['rate-limit', 'API', 'DoS'],
    reincidencia: 0,
    historico: historicoPadrao,
    notificacoesEnviadas: 1,
    status: 'Em Backlog',
    comentarios: []
  },
  {
    id: 'VULN-008',
    titulo: 'Header de segurança ausente',
    descricaoExecutiva: 'Headers de segurança HTTP não estão configurados corretamente.',
    descricaoTecnica: 'Ausência de X-Frame-Options, X-Content-Type-Options e Strict-Transport-Security.',
    criticidade: 'Informativa',
    scoreCvss: 3.1,
    cwe: 'CWE-693',
    owaspCategory: 'A05:2025-Security Misconfiguration',
    squad: 'DevOps',
    responsavel: 'Lucas Ferreira',
    gestor: 'Roberto Alves',
    sistema: 'Portal do Cliente',
    ativo: 'web-app',
    ambiente: 'Produção',
    origem: 'SCA',
    dataCriacao: '2025-03-05',
    ultimaAtualizacao: '2025-03-10',
    sla: '2025-05-05',
    diasEmAberto: 8,
    recomendacao: 'Configurar headers de segurança no nginx/CDN.',
    tags: ['headers', 'configuração', 'hardening'],
    reincidencia: 0,
    historico: historicoPadrao,
    notificacoesEnviadas: 0,
    status: 'Aberta',
    comentarios: []
  },
  {
    id: 'VULN-009',
    rtcWorkItemId: 'WI-1242',
    titulo: 'Autenticação fraca em API interna',
    descricaoExecutiva: 'API interna utiliza autenticação básica sem criptografia adequada.',
    descricaoTecnica: 'Serviço interno usa Basic Auth sobre HTTP, expondo credenciais em texto plano.',
    criticidade: 'Crítica',
    scoreCvss: 8.1,
    vetorCvss: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N',
    cwe: 'CWE-287',
    owaspCategory: 'A07:2025-Authentication Failures',
    squad: 'Infraestrutura',
    responsavel: 'Lucas Ferreira',
    gestor: 'Roberto Alves',
    sistema: 'Microserviços',
    ativo: 'internal-api',
    ambiente: 'Staging',
    endpoint: '/internal/data',
    metodoHttp: 'GET',
    origem: 'Pentest',
    dataCriacao: '2025-01-20',
    ultimaAtualizacao: '2025-03-01',
    sla: '2025-02-20',
    diasEmAberto: 52,
    recomendacao: 'Migrar para mTLS ou OAuth2 com tokens JWT.',
    tags: ['autenticação', 'interno', 'criptografia'],
    reincidencia: 1,
    historico: historicoPadrao,
    notificacoesEnviadas: 6,
    status: 'Aberta',
    comentarios: []
  },
  {
    id: 'VULN-010',
    titulo: 'SSRF no serviço de preview',
    descricaoExecutiva: 'Serviço de preview de URLs permite requisições para hosts internos.',
    descricaoTecnica: 'O endpoint /api/preview aceita URLs arbitrárias sem validação de destino.',
    criticidade: 'Crítica',
    scoreCvss: 9.1,
    vetorCvss: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:L/A:L',
    cwe: 'CWE-918',
    owaspCategory: 'A10:2025-SSRF',
    squad: 'Backend',
    responsavel: 'Ana Costa',
    gestor: 'Pedro Lima',
    sistema: 'Portal do Cliente',
    ativo: 'preview-service',
    componente: 'URLPreviewController',
    ambiente: 'Produção',
    endpoint: '/api/preview',
    metodoHttp: 'POST',
    parametroAfetado: 'url',
    origem: 'Pentest',
    dataCriacao: '2025-03-08',
    ultimaAtualizacao: '2025-03-12',
    sla: '2025-03-15',
    diasEmAberto: 5,
    recomendacao: 'Implementar allowlist de domínios. Bloquear IPs internos e metadata endpoints.',
    tags: ['SSRF', 'network', 'crítico'],
    reincidencia: 0,
    historico: historicoPadrao,
    notificacoesEnviadas: 3,
    status: 'Em Correção',
    comentarios: []
  },
]

export const squads: Squad[] = [
  { nome: 'API Core', vulnerabilidades: 15, criticas: 3, vencidas: 2 },
  { nome: 'Backend', vulnerabilidades: 22, criticas: 5, vencidas: 4 },
  { nome: 'Frontend', vulnerabilidades: 8, criticas: 1, vencidas: 0 },
  { nome: 'DevOps', vulnerabilidades: 12, criticas: 2, vencidas: 1 },
  { nome: 'Infraestrutura', vulnerabilidades: 10, criticas: 2, vencidas: 2 },
  { nome: 'Mobile', vulnerabilidades: 5, criticas: 0, vencidas: 0 },
]

export const notificacoes: Notificacao[] = [
  {
    id: 'NOT-001',
    tipo: 'critica',
    titulo: 'Vulnerabilidade crítica identificada',
    descricao: 'SQL Injection no endpoint de autenticação requer ação imediata.',
    dataEnvio: '2025-03-12T10:30:00',
    squad: 'API Core',
    vulnerabilidadeId: 'VULN-001'
  },
  {
    id: 'NOT-002',
    tipo: 'vencida',
    titulo: 'SLA vencido - VULN-002',
    descricao: 'Broken Access Control passou do prazo de correção.',
    dataEnvio: '2025-03-11T09:00:00',
    squad: 'Backend',
    vulnerabilidadeId: 'VULN-002'
  },
  {
    id: 'NOT-003',
    tipo: 'sla',
    titulo: 'SLA próximo do vencimento',
    descricao: 'SSRF no serviço de preview vence em 3 dias.',
    dataEnvio: '2025-03-12T08:00:00',
    squad: 'Backend',
    vulnerabilidadeId: 'VULN-010'
  },
  {
    id: 'NOT-004',
    tipo: 'resumo',
    titulo: 'Resumo semanal de vulnerabilidades',
    descricao: '5 novas vulnerabilidades, 3 corrigidas, 2 vencidas.',
    dataEnvio: '2025-03-10T07:00:00',
    squad: 'Todos'
  },
]

export const regrasNotificacao: RegraNotificacao[] = [
  { id: 'REGRA-001', nome: 'Críticas imediatas', condicao: 'Criticidade Crítica', ativa: true, canal: 'email' },
  { id: 'REGRA-002', nome: 'Vencidas > 7 dias', condicao: 'SLA vencido há mais de 7 dias', ativa: true, canal: 'email' },
  { id: 'REGRA-003', nome: 'Próximo vencimento', condicao: 'SLA vence em menos de 3 dias', ativa: true, canal: 'email' },
  { id: 'REGRA-004', nome: 'Resumo semanal', condicao: 'Segunda-feira às 07:00', ativa: true, canal: 'email' },
  { id: 'REGRA-005', nome: 'Sem responsável > 48h', condicao: 'Vulnerabilidade sem responsável há 48h', ativa: false, canal: 'email' },
]

export const integracaoRtc: IntegracaoRtc = {
  status: 'conectado',
  urlInstancia: 'https://rtc.example.com',
  projetosMonitorados: ['SEC', 'VULN', 'APPSEC'],
  ultimaSincronizacao: '2025-03-12T14:30:00',
  workItemsImportados: 156
}

export const estatisticas = {
  totalAbertas: 47,
  criticas_total: 2,
  criticas: 8,
  vencidas: 12,
  mediadiasAberto: 28,
  semResponsavel: 5,
  corrigidasPeriodo: 23,
  notificacoesHoje: 8,
  regrasAtivas: 4,
}

export const owaspDistribuicao = [
  { categoria: 'A01:2025-Broken Access Control', quantidade: 15 },
  { categoria: 'A02:2025-Cryptographic Failures', quantidade: 8 },
  { categoria: 'A03:2025-Injection', quantidade: 12 },
  { categoria: 'A04:2025-Insecure Design', quantidade: 5 },
  { categoria: 'A05:2025-Security Misconfiguration', quantidade: 10 },
  { categoria: 'A06:2025-Vulnerable Components', quantidade: 7 },
  { categoria: 'A07:2025-Authentication Failures', quantidade: 9 },
  { categoria: 'A08:2025-Data Integrity Failures', quantidade: 3 },
  { categoria: 'A09:2025-Logging Failures', quantidade: 4 },
  { categoria: 'A10:2025-SSRF', quantidade: 2 },
]

export const cweDistribuicao = [
  { cwe: 'CWE-89', nome: 'SQL Injection', quantidade: 8 },
  { cwe: 'CWE-79', nome: 'XSS', quantidade: 12 },
  { cwe: 'CWE-639', nome: 'IDOR', quantidade: 7 },
  { cwe: 'CWE-287', nome: 'Auth Bypass', quantidade: 5 },
  { cwe: 'CWE-918', nome: 'SSRF', quantidade: 3 },
  { cwe: 'CWE-532', nome: 'Log Exposure', quantidade: 4 },
]

export const evolucaoMensal = [
  { mes: 'Out', abertas: 45, corrigidas: 12 },
  { mes: 'Nov', abertas: 38, corrigidas: 20 },
  { mes: 'Dez', abertas: 52, corrigidas: 18 },
  { mes: 'Jan', abertas: 41, corrigidas: 25 },
  { mes: 'Fev', abertas: 35, corrigidas: 28 },
  { mes: 'Mar', abertas: 47, corrigidas: 23 },
]

export const agingDistribuicao = [
  { faixa: '0-7 dias', quantidade: 12 },
  { faixa: '8-15 dias', quantidade: 8 },
  { faixa: '16-30 dias', quantidade: 10 },
  { faixa: '31-60 dias', quantidade: 9 },
  { faixa: '> 60 dias', quantidade: 8 },
]
